<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.13.0" />  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Region42.ScoresStandings.Domain\Region42.ScoresStandings.Domain.csproj" />
  </ItemGroup>

</Project>